/*
 * This source file was generated by the Gradle 'init' task
 */
package team.project;

import team.project.datacollection.*;
import team.project.analysis.GPTClient;
import java.util.List;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Crawler naverCrawler = new Crawler();
        // naverCrawler.crawl();
        // List<String> articles = naverCrawler.getArticlesString();
        // System.out.println(articles.size());
        // for(String article: articles) {
        //     System.out.println(article);
        //     System.out.println("\n\n");
        // }
        GPTClient client = new GPTClient();
        client.execute();

    }
}
